### ISSUE TITLE
why not DKI model?

### ISSUE THREAD

**Issue by foxet** [AthenaEPI/dmipy#65]
dmipy is a great tool to me, but why no dki model here?  :)

**Comment by rutgerfick** [comment]
Great to hear that! It's been a passion project for me now that I've moved on to radiotherapy, so I'm happy it's of use to you :-)

DKI is not here mostly because I have to draw the line in the sand somewhere.
I scoped Dmipy for multi-compartment modeling only, as signal models are already available at dipy and others (they have the whole range of DTI/DKI/MAPMRI/qt-dMRI).
